import os

MQTT_BROKER_ADDRESS = os.environ.get("MQTT_BROKER_ADDRESS")
MQTT_BROKER_PORT = os.environ.get("MQTT_BROKER_PORT")
MQTT_TOPIC_TEMPERATURE = os.environ.get("MQTT_TOPIC_TEMPERATURE")
MQTT_TOPIC_HUMIDITY = os.environ.get("MQTT_TOPIC_HUMIDITY")
MQTT_TOPIC_MOISTURE = os.environ.get("MQTT_TOPIC_MOISTURE")